println(" Testing module Utils" )
include("testSparseUtils.jl")
include("testSortpermFast.jl")
include("testUniqueIdx.jl")
include("testVariousUtils.jl")
include("testTests.jl")
println(" Utils: All tests passed" )
