println("test getDataParallel")
include("testGetDataParallel.jl")
println("test prepareMesh2Mesh")
include("testPrepareMesh2Mesh.jl")
println("test test utilities")
include("testTest.jl")
include("testGetSensMat.jl")
include("testClear.jl")